pipelines:
  branches: # Branch-specific pipelines definitions
    develop:
      - step:
          name: Build and test the app
          image: node:16.14.2
          script:
            - npm install
            - CI=false npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              deployment: Dev
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET_NAME
                ACL: "public-read"
                LOCAL_PATH: "build"
