
  const TEXT = 'TEXT'
  const MEMO = 'MEMO'
  const QUICKPICK = 'QUICKPICK'
  const NUMBER = 'NUMBER'
  const BIT = 'BIT'
  const DATETIME='DATETIME'
  const DATE = 'DATE'
  const MULTIPICK = 'MULTIPICK'
  const THREEPANE= '3PANE'
  const CONCAT = 'CONCAT'
  const IMAGE = 'IMAGE'
  const GUID = 'GUID'
  const MACADDR = 'MACADDR'

  const CHARACTER_SPACE = ' , '
  const MAX_LENGTH = 1000
  const MAX_LENGTH_NUMERIC = 20

  const TEXT_WIDTH = 50
  const QUICKPICK_WIDTH = 50
  const MULTIPICK_WIDTH = 50
  const CONCAT_WIDTH = 50
  const NUMBER_WIDTH = 20
  const BIT_WIDTH = 20
  const DATE_WIDTH = 15
  const DATETIME_WIDTH = 25

  const UNSORTED = 'unsorted'
  const SORT_ASC = 'sort-asc'
  const SORT_DESC = 'sort-desc'

  const EXPRESSION = 'expression'
  
  const TOP = 'TOP'
  const BASE = 'BASE'
  const POINT_TYPE = 'POINT.Type'
  const POINT_NAME = 'POINT'

  const MAX_FEATURES_ON_GRID = 8

  const SUCCESS_NOTIFI = 'success'
  const ERROR_NOTIFI = 'error'
  const INFO_NOTIFI = 'info'
  const WARNING_NOTIFI = 'warning'
  const NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED'

export {
  TEXT,
  MEMO,
  QUICKPICK,
  BIT,
  NUMBER,
  DATETIME,
  DATE,
  MULTIPICK,
  THREEPANE,
  CHARACTER_SPACE,
  MAX_LENGTH,
  MAX_LENGTH_NUMERIC,
  CONCAT,
  TEXT_WIDTH,
  QUICKPICK_WIDTH,
  MULTIPICK_WIDTH,
  CONCAT_WIDTH,
  NUMBER_WIDTH,
  BIT_WIDTH,
  DATE_WIDTH,
  DATETIME_WIDTH,
  IMAGE,
  UNSORTED,
  SORT_ASC,
  SORT_DESC,
  EXPRESSION,
  TOP,
  BASE,
  POINT_TYPE,
  POINT_NAME,
  MAX_FEATURES_ON_GRID,
  GUID,
  MACADDR,
  SUCCESS_NOTIFI,
  ERROR_NOTIFI,
  INFO_NOTIFI,
  WARNING_NOTIFI,
  NEW_PASSWORD_REQUIRED,
}
