export default {
  titleScreen1: 'Title screen 1',
  titleScreen2: 'Title screen 2',
  titleExportDataFormScreen: 'Save point options',
  notAvailable: 'This feature is not available',
  storageAccess: 'Storage access!',
  permissionFeature: 'allow use of this feature in settings.',
  getLocation: 'Get Location',
  useGPS: 'Use Tablet onboard GPS to capture POINT location?',
  descriptionGPS: '(Will overwrite existing fields)',
  attachPicture: 'Attach Picture',
  takePhoto: 'Take photo now?',
  createChild: 'Create new child of selected layer?',
  createLayer: 'Create new layer from copy of selected layer?',
  descriptionCreateLayer: '(the following fields will be cleared and will need be populated.)',
  copyLocation: 'Create new location from copy of selected location?',
  descriptionCopyLocation:
    '(the following fields will be cleared and will need to be populated.)',
  hintCopyLocation: '(Hint: Use ‘Get Location’ to populate location features)',
  savePointCloud: 'Save point to cloud (online)',
  descriptionSavePointCloud:
    'This action will save the point as an XML file on the cloud server. You can access the file on the cloud server and import into Core-GS using XML import tool.',
  requireSaveCloud: 'Requires a reliable internet connection (i.e. online)',
  cloudAlertTitle: 'Save point to cloud server?',
  cloudAlertDescription: 'This action will save the point to the cloud server. Only works in online mode. If offline, use \'save point to table\' instead.',
  savePointTable: 'Save point to tablet (offline)',
  descriptionSavePointTable:
    'This action will save the point to the tablet\'s fileSystem. You can download the xml file and import into Core-GS using CoreGS XML import tool',
  tableAlertTitle: 'Save point to tablet filesystem?',
  tableAlertDescription: 'This action will save the point to the table\'s filesystem as XML file. Use when in offline mode to make periodic backups.',
  requireSaveTable: 'Use when you dont\'t have a reliable internet connection.',
  moreDescriptionSaveTable: 'You can save point to XML file as many times as you want (snapshots). You only have to download and import the latest version of the XML file into CoreGS.',
  saveToCloud: 'Save to cloud',
  saveXMLFile: 'Save XML file',
  loadSnapshot: 'Load snapshot back-up ?',
  descriptionLoadSnapshot:
    '(this will push a snapshot of point to server. Future changes will be permitted)',
  loadSpecification: 'Load specification for new point ?',
  descriptionloadSpecification:
    '(load specification for new (assigned) point from server)',
  warningConstraint: 'Wrong constraint of this feature',
  warningRequireFeature: 'This is a require feature',
  warningFloatNumber: 'warning message for float number',
  warningNumberMinMax: 'Value of {0} must be in the range of [{1}]',
  warningDecimalNumber: 'Number must be between {0} and {1}',
  warningIntegerNumber: 'Wrong integer number format',
  warningLimitCharacters: 'Your input has reached the limit',
  titleSave: 'Save',
  warningOverwritePhoto: 'Do you want to save this change?',
  titleDelete: 'Delete',
  titleClear: 'Clear current feature selection',
  confirmDelete: 'Do you want to delete the record?',
  confirmDeleteItem: 'Do you want to clear current feature selection?',
  titleLocation: 'Get location',
  titleChangeOption: 'Change dropdown option',
  titleChangeTypePoint: 'Change option',
  messageChangeTypePoint: 'Warning child records will be deleted.',
  messageChangeOption: 'Do you want to select another dropdown option? All existing selections will be lost.',
  confirmEditLocation: 'Are you sure you want to edit this location?',
  warningQickPick: 'You need to choose one of the options in order to proceed to the next step.',
  warningEmpty: 'This field is required.',
  warningDecimalPoint : 'Your input must contain no more than 1 decimal point.',
  warningGoBack : 'There is unsaved data. All data will be lost. Do you want to cancel record entry?',
  warning : 'Warning',
  warningExistedRecord: 'Cannot save. Record identifier will not be unique. Please correct the data.',
  valueInvalid: 'This value is invalid.',
  baseOrBaseInvalid: 'Value of Base or Top invalid',
  connection: 'Connection',
  connectionDescription: 'Please connect to internet.',
  uploadError: 'Upload Error',
  uploadErrorDescription: 'we\'re experiencing technical difficulties, please try again later.',
  uploadPoint: 'Publish point',
  successfully: 'successfully.',
  error: 'Error',
}
