import { FormType } from './formtype'
import {
  Water, PROJECT, Progress, TT_FLDCA_ScalaPenetrometer, DiscontinuityWithImage,
  Backfill, Flush, Vane, Fracture, Casing,
  GeologyDetail, SAMPLE, GEOLOGY, ConstructionSPT, TT_FLDCA_Piezometer,
  ExcavationImage, POINT, CoreImage
} from './features'

export const Workflow = [
{
  level: 0,
  name: '1Level',
  formtype: FormType.TwoPane,
  displayName: 'Level 1',
  parent: null,
  order: 10,
  relevant: '',
  navigation: PROJECT,
},
{
  level: 0,
  name: '2Level',
  formtype: FormType.TwoPane,
  displayName: 'Level 2',
  parent: null,
  order: 10,
  relevant: '',
  navigation: PROJECT,
  children: 
  [
    {
      level: 1,
      name: 'Level2-1',
      formtype: FormType.TwoPane,
      displayName: 'Level 2-1',
      parent: 'PROJECT',
      order: 10,
      relevant: '',
      navigation: POINT,
    },
    {
      level: 1,
      name: 'Level2-2',
      formtype: FormType.TwoPane,
      displayName: 'Level 2-2',
      parent: 'PROJECT',
      order: 10,
      relevant: '',
      navigation: POINT,
    },
    {
      level: 1,
      name: 'Level2-2',
      formtype: FormType.TwoPane,
      displayName: 'Leve',
      parent: 'PROJECT',
      order: 10,
      relevant: '',
      navigation: POINT,
    }
  ]
},
{
  level: 0,
  name: '4Level',
  formtype: FormType.TwoPane,
  displayName: 'Level 4',
  parent: null,
  order: 10,
  relevant: '',
  navigation: PROJECT,
  children: 
  [
    {
      level: 1,
      name: 'Level1',
      formtype: FormType.TwoPane,
      displayName: 'Level 1',
      parent: 'PROJECT',
      order: 10,
      relevant: '',
      navigation: POINT,
      children: 
        [
          {
            level: 2,
            name: 'Level3',
            formtype: FormType.TwoPane,
            displayName: 'Level 3',
            parent: 'POINT',
            order: 25,
            relevant: '',
            navigation: ConstructionSPT,
            children: [
                        {              
                          level: 3,
                          name: 'Level4',
                          formtype: FormType.TwoPane,
                          displayName: 'Level 4',
                          parent: 'ConstructionSPT',
                          order: 10,
                          relevant: '',
                          navigation: PROJECT,
                        }
            ],
          },
        ]
    },
  ],
}

  // level: 0,
  // name: 'PROJECT1',
  // formtype: FormType.TwoPane,
  // displayName: 'Project1',
  // parent: null,
  // order: 10,
  // relevant: '',
  // navigation: PROJECT,
  // children: 
  // [
  //   {
  //     level: 1,
  //     name: 'POINT',
  //     formtype: FormType.TwoPane,
  //     displayName: 'Point',
  //     parent: 'PROJECT',
  //     order: 10,
  //     relevant: '',
  //     navigation: POINT,
  //   },
  // ],
  // level: 0,
  // name: 'PROJECT2',
  // formtype: FormType.TwoPane,
  // displayName: 'Project2',
  // parent: null,
  // order: 10,
  // relevant: '',
  // navigation: PROJECT,
  // children: 
  // [
  //   {
  //     level: 1,
  //     name: 'POINT3',
  //     formtype: FormType.TwoPane,
  //     displayName: 'Point',
  //     parent: 'PROJECT',
  //     order: 10,
  //     relevant: '',
  //     navigation: POINT,
  //     children: 
  //     [
  //       {
  //         level: 2,
  //         name: 'ConstructionSPT',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Method (incl. SPT)',
  //         parent: 'POINT',
  //         order: 25,
  //         relevant: '',
  //         navigation: ConstructionSPT,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'GEOLOGY',
  //         formtype: FormType.ThreePane,
  //         displayName: 'Geology',
  //         parent: 'POINT',
  //         order: 30,
  //         relevant: '',
  //         navigation: GEOLOGY,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'GeologyDetail',
  //         formtype: FormType.ThreePane,
  //         displayName: 'Geology Detail',
  //         parent: 'POINT',
  //         order: 40,
  //         relevant: '',
  //         navigation: GeologyDetail,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Vane',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Shear Vane',
  //         parent: 'POINT',
  //         order: 50,
  //         relevant: '',
  //         navigation: Vane,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'TT_FLDCA_ScalaPenetrometer',
  //         formtype: FormType.ThreePane,
  //         displayName: 'Dynamic Penetration Test (Scala)',
  //         parent: 'POINT',
  //         order: 75,
  //         relevant: '',
  //         navigation: TT_FLDCA_ScalaPenetrometer,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'DiscontinuityWithImage',
  //         formtype: FormType.ThreePane,
  //         displayName: 'Discontinuity',
  //         parent: 'POINT',
  //         order: 95,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC" || POINT.Type == "TP"',
  //         navigation: DiscontinuityWithImage,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Fracture',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Fracture Spacing',
  //         parent: 'POINT',
  //         order: 100,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC"',
  //         navigation: Fracture,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Progress',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Time Remark (incl. GWL readings)',
  //         parent: 'POINT',
  //         order: 110,
  //         relevant: '',
  //         navigation: Progress,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'SAMPLE',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Sample (excl. SPT and push tube)',
  //         parent: 'POINT',
  //         order: 130,
  //         relevant: '',
  //         navigation: SAMPLE,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Casing',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Casing / Shoring',
  //         parent: 'POINT',
  //         order: 140,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC"',
  //         navigation: Casing,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Flush',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Circulation / Flush',
  //         parent: 'POINT',
  //         order: 150,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC"',
  //         navigation: Flush,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Water',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Water Strike',
  //         parent: 'POINT',
  //         order: 160,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC" || POINT.Type == "TP" || POINT.Type == "HA" || POINT.Type == "PR"',
  //         navigation: Water,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'TT_FLDCA_Piezometer',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Piezometer Installation',
  //         parent: 'POINT',
  //         order: 170,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC" || POINT.Type == "TP" || POINT.Type == "HA" || POINT.Type == "PR"',
  //         navigation: TT_FLDCA_Piezometer,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'Backfill',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Backfill',
  //         parent: 'POINT',
  //         order: 180,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC" || POINT.Type == "TP" || POINT.Type == "HA" || POINT.Type == "PR"',
  //         navigation: Backfill,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'CoreImage',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Core Image (incl. core box ref)',
  //         parent: 'POINT',
  //         order: 190,
  //         relevant: 'POINT.Type == "RC" || POINT.Type == "SNC" || POINT.Type == "HA"',
  //         navigation: CoreImage,
  //         children: [],
  //       },
  //       {
  //         level: 2,
  //         name: 'ExcavationImage',
  //         formtype: FormType.TwoPane,
  //         displayName: 'Excavation Image',
  //         parent: 'POINT',
  //         order: 200,
  //         relevant: 'POINT.Type == "TP"',
  //         navigation: ExcavationImage,
  //         children: [],
  //       },
  //     ],
  //   },
  // ],
]